name: Build SC2 Map Artifacts

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "build_sc2map.py"
      - "maps/**"
      - "mods/**"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        map:
          - PylonAIE_5_0_14
          - MagannathaAIE_5_0_14
          - UltraloveAIE_5_0_14
          - LeyLinesAIE_5_0_14
          - TorchesAIE_5_0_14
          - PersephoneAIE_5_0_14

    steps:
      - uses: actions/checkout@v4

      - name: ðŸ”„ Build SC2 Map
        uses: ./.github/actions/shared-build-map
        with:
          map: ${{ matrix.map }}

      - name: ðŸ“¤ Upload SC2Map Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.map }}
          path: Output/${{ matrix.map }}.SC2Map
